#!/bin/bash

set -e

cd "${1}"

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

PATH=/usr/local/bin:$PATH

PAYLOAD=$(mktemp /tmp/resource-in.XXXXXX)

cat > "$PAYLOAD" <&0

MQTT_HOST="$(jq -r '.source.MQTT_HOST' < "${PAYLOAD}")"
MQTT_PORT="$(jq -r '.source.MQTT_PORT' < "${PAYLOAD}")"
MQTT_USER="$(jq -r '.source.MQTT_USER' < "${PAYLOAD}")"
MQTT_PASS="$(jq -r '.source.MQTT_PASS' < "${PAYLOAD}")"
MQTT_TOPIC="$(jq -r '.source.MQTT_TOPIC' < "${PAYLOAD}")"
API_CMD="$(jq -r '.params.API_CMD' < "${PAYLOAD}")"

mosquitto_pub -h MQTT_HOST -p $MQTT_PORT -u $MQTT_USER -P $MQTT_PASS -t $MQTT_TOPIC -m "$API_CMD"

timestamp="$(jq -n "{version:{timestamp:\"$(date +%s)\"}}")"
echo "$timestamp $metadata $debug_info " | jq -s add  >&3
